# Generated by Django 3.2.5 on 2021-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('mobile', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
